### ISSUE TITLE
Run Command after clone

### ISSUE THREAD

**Issue by obcode** [obcode/glabs#14]

**Comment by obcode** [comment]
Config should be:

```yml
clone:
  ...
  run:
    cmd: echo "hello"
    outfile: logs.txt
    fork: true # run in go routine 
```

should **never** run automatically. Needs flag `-r`/`--run`.
